import sys
from pathlib import Path


def get_types_content():
    project_root = Path(__file__).parent.parent.parent.parent.parent.parent

    # Check new monorepo config directory first
    labels_path = project_root / "config" / "smart_stable_model_config.toml"

    if not labels_path.exists():
        # Fallback to legacy path just in case
        legacy_path = (
            project_root / "src/smartstablemodel/config/smart_stable_model_config.toml"
        )
        if legacy_path.exists():
            labels_path = legacy_path
        else:
            print(f"Error: labels config not found at {labels_path} or {legacy_path}")
            return None

    try:
        try:
            import tomllib
        except ImportError:
            import tomli as tomllib

        with open(labels_path, "rb") as f:
            data = tomllib.load(f)
    except Exception as e:
        print(f"Error parsing labels config: {e}")
        return None

    labels = data.get("labels", [])
    label_values = [label["value"] for label in labels]

    # Gather groups
    groups = {}
    for label in labels:
        g = label.get("label_group")
        if g:
            if g not in groups:
                groups[g] = []
            groups[g].append(label["value"])

    # Sort for consistency
    label_values.sort()
    for g in groups:
        groups[g].sort()

    content = [
        "# This file is automatically generated by tools/generate_types.py",
        "# Do not modify this file directly.",
        "",
        "from typing import Literal",
        "from typing_extensions import TypedDict",
        "",
        "LabelValue = Literal[",
    ]

    for value in label_values:
        content.append(f'    "{value}",')
    content.append("]")
    content.append("")

    content.append("class LabelProbabilities(TypedDict, total=False):")
    for value in label_values:
        content.append(f"    {value}: float")

    content.append("")

    # Generate group lists
    for group_name, values in sorted(groups.items()):
        const_name = f"{group_name.upper()}_VOCALIZATIONS"
        content.append(f"{const_name} = {{")
        for v in values:
            content.append(f'    "{v}",')
        content.append("}")
        content.append("")

    return "\n".join(content)


def generate_types():
    project_root = Path(__file__).parent.parent.parent.parent
    output_path = project_root / "src/smartstablemodel/generated_types.py"

    content = get_types_content()
    if content is None:
        return

    with open(output_path, "w") as f:
        f.write(content)

    print(f"Successfully generated types at {output_path}")


def check_and_update():
    """
    Checks if the generated types file matches the config.
    If not, prints a warning and updates the file.
    """
    project_root = Path(__file__).parent.parent.parent.parent
    output_path = project_root / "src/smartstablemodel/generated_types.py"

    expected_content = get_types_content()
    if expected_content is None:
        return

    current_content = ""
    if output_path.exists():
        with open(output_path, "r") as f:
            current_content = f.read()

    if current_content != expected_content:
        print("!" * 80)
        print(
            "WARNING: generated_types.py was out of sync with smart_stable_model_config.toml!"
        )
        print(f"Updating {output_path}...")
        print("!" * 80)

        try:
            with open(output_path, "w") as f:
                f.write(expected_content)
            print("Successfully updated generated_types.py")
        except OSError as e:
            print(f"ERROR: Could not update generated_types.py: {e}")
            print("Please run the generation script manually locally:")
            print("python src/smartstablemodel/tools/generate_types.py")
    else:
        print("generated_types.py is in sync with config.")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        check_and_update()
    else:
        generate_types()
