# This file is automatically generated by tools/generate_types.py
# Do not modify this file directly.

from typing import Literal
from typing_extensions import TypedDict

LabelValue = Literal[
    "anomaly_abnormal",
    "anomaly_normal",
    "background",
    "bird_tweet",
    "bird_wing_flap",
    "change_stance",
    "coughing",
    "defecating",
    "dog_barking",
    "drinking",
    "eating",
    "eating_trial",
    "groan",
    "horse_kick",
    "human_cough",
    "human_scream",
    "human_talking",
    "neigh",
    "nicker",
    "other",
    "other_animals",
    "other_impact",
    "panting",
    "pawing",
    "rattle",
    "rolling",
    "scream",
    "silence",
    "sleeping_breathing",
    "sleeping_snoring",
    "snort",
    "squeal",
    "unsure",
    "urinating",
    "walking",
    "whimmering",
]

class LabelProbabilities(TypedDict, total=False):
    anomaly_abnormal: float
    anomaly_normal: float
    background: float
    bird_tweet: float
    bird_wing_flap: float
    change_stance: float
    coughing: float
    defecating: float
    dog_barking: float
    drinking: float
    eating: float
    eating_trial: float
    groan: float
    horse_kick: float
    human_cough: float
    human_scream: float
    human_talking: float
    neigh: float
    nicker: float
    other: float
    other_animals: float
    other_impact: float
    panting: float
    pawing: float
    rattle: float
    rolling: float
    scream: float
    silence: float
    sleeping_breathing: float
    sleeping_snoring: float
    snort: float
    squeal: float
    unsure: float
    urinating: float
    walking: float
    whimmering: float

DISTRESS_VOCALIZATIONS = {
    "horse_kick",
    "scream",
    "squeal",
    "whimmering",
}

DRINKING_VOCALIZATIONS = {
    "drinking",
}

EATING_VOCALIZATIONS = {
    "eating",
    "eating_trial",
}

MOVEMENT_VOCALIZATIONS = {
    "change_stance",
    "pawing",
    "rolling",
    "walking",
}

OTHER_VOCALIZATIONS = {
    "anomaly_abnormal",
    "anomaly_normal",
    "background",
    "bird_tweet",
    "bird_wing_flap",
    "defecating",
    "dog_barking",
    "groan",
    "human_cough",
    "human_scream",
    "human_talking",
    "neigh",
    "nicker",
    "other",
    "other_animals",
    "other_impact",
    "rattle",
    "silence",
    "snort",
    "unsure",
    "urinating",
}

RESPIRATORY_VOCALIZATIONS = {
    "coughing",
    "panting",
}

SLEEPING_VOCALIZATIONS = {
    "sleeping_breathing",
    "sleeping_snoring",
}
